"""Added GPS tracking

Peek Plugin Database Migration Script

Revision ID: cb1f734aaa25
Revises: 6bf6ecef3108
Create Date: 2021-02-11 14:30:17.931079

"""

# revision identifiers, used by Alembic.
revision = "cb1f734aaa25"
down_revision = "6bf6ecef3108"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GpsLocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deviceId", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("updatedDate", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deviceId"],
            ["core_device.DeviceInfo.deviceId"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deviceId"),
        schema="core_device",
    )
    op.create_table(
        "GpsLocationHistory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("deviceId", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("loggedDate", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deviceId"],
            ["core_device.DeviceInfo.deviceId"],
        ),
        sa.PrimaryKeyConstraint("id", "deviceId", "loggedDate"),
        schema="core_device",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("GpsLocationHistory", schema="core_device")
    op.drop_table("GpsLocation", schema="core_device")
    # ### end Alembic commands ###
