"""Added filePath to update

Peek Plugin Database Migration Script

Revision ID: cfc0c77e37ae
Revises: 5de087ace66f
Create Date: 2017-06-24 11:50:37.218266

"""

# revision identifiers, used by Alembic.
revision = 'cfc0c77e37ae'
down_revision = '5de087ace66f'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeviceUpdate',
                  sa.Column('filePath', sa.String(length=150), nullable=False),
                  schema='core_device')
    op.alter_column('DeviceUpdate', 'isEnabled', type_=sa.String(length=150),
                    server_default='0', schema='core_device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeviceUpdate', 'filePath', schema='core_device')
    # ### end Alembic commands ###
